variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build-linux:
  stage: build
  script:
    - conda build ./conda --prefix-length=80 --output-folder=dist/ --channel=http://bcu-ci.esrf.fr/stable
  artifacts:
    paths:
      - dist/
  tags:
    - conda
    - linux

build-win:
  stage: build
  script:
    - conda build ./conda --prefix-length=80 --output-folder=dist/ --channel=http://bcu-ci.esrf.fr/stable
  artifacts:
    paths:
      - dist/
  tags:
    - conda
    - win

deploy:
  stage: deploy
  environment:
    name: production
    url: http://bcu-ci.esrf.fr/stable
  dependencies:
    - build-linux
    - build-win
  script:
    - cp -Rf dist/* /conda/
    - conda index /conda/
  tags:
    - conda
    - linux
  when: manual
