# Strip the 'v' from the version tag
{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-core
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
    - python {{ python }} #Python is used by CMake configure stage
    - numpy
    - sip 4.18*           #For the SIP generator
  host:
    - processlib
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c 1.8.2
    - hdf5 1.10*
    - libtiff
    - cbflib        # [linux]
    - openssl       # [linux]
  run:
    - python {{ python }}
    - sip 4.18*
    - numpy
    - {{ pin_compatible('processlib', max_pin='x.x') }}
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c 1.8.2
    - hdf5 1.10*
    - libtiff
    - cbflib        # [linux]

test:
  requires:
    - cmake
    - python {{ python }}
  imports:
    - Lima.Core
  #commands:
  #  - cd build
  #  - ctest --timeout 10 --output-on-failure

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
